/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.TaskController;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;
import model.Task;

/**
 *
 * @author Windows 7
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    TaskController controller;
    Project project; // vai ser o projeto dono dessa tarafa | fk
    
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBar = new javax.swing.JPanel();
        jLabelToolBarTask = new javax.swing.JLabel();
        jLabelToolBarIcon = new javax.swing.JLabel();
        jPanelMainTab = new javax.swing.JPanel();
        jLabelMainTabNome = new javax.swing.JLabel();
        jTextFieldMainTabNome = new javax.swing.JTextField();
        jLabelMainTabDescricao = new javax.swing.JLabel();
        jScrollPaneMainTabDescricao = new javax.swing.JScrollPane();
        jTextAreaMainTabDescricao = new javax.swing.JTextArea();
        jLabelMainTabPrazo = new javax.swing.JLabel();
        jLabelMainTabNotas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNotas = new javax.swing.JTextArea();
        jFormattedTextPrazo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelToolBar.setBackground(new java.awt.Color(0, 175, 121));

        jLabelToolBarTask.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelToolBarTask.setForeground(java.awt.Color.white);
        jLabelToolBarTask.setText("Tarefa");

        jLabelToolBarIcon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelToolBarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        jLabelToolBarIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelToolBarIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelToolBarTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelToolBarIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelToolBarTask, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelToolBarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelMainTab.setBackground(java.awt.Color.white);

        jLabelMainTabNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMainTabNome.setText("Nome");

        jTextFieldMainTabNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelMainTabDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMainTabDescricao.setText("Descrição");

        jTextAreaMainTabDescricao.setColumns(20);
        jTextAreaMainTabDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaMainTabDescricao.setRows(5);
        jScrollPaneMainTabDescricao.setViewportView(jTextAreaMainTabDescricao);

        jLabelMainTabPrazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMainTabPrazo.setText("Prazo");

        jLabelMainTabNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMainTabNotas.setText("Notas");

        jTextAreaNotas.setColumns(20);
        jTextAreaNotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaNotas.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNotas);

        javax.swing.GroupLayout jPanelMainTabLayout = new javax.swing.GroupLayout(jPanelMainTab);
        jPanelMainTab.setLayout(jPanelMainTabLayout);
        jPanelMainTabLayout.setHorizontalGroup(
            jPanelMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMainTabNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMainTabNome)
                    .addComponent(jLabelMainTabDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneMainTabDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addComponent(jLabelMainTabPrazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMainTabNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jFormattedTextPrazo))
                .addContainerGap())
        );
        jPanelMainTabLayout.setVerticalGroup(
            jPanelMainTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMainTabNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMainTabNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMainTabDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneMainTabDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMainTabPrazo)
                .addGap(4, 4, 4)
                .addComponent(jFormattedTextPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMainTabNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMainTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelToolBarIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelToolBarIconMouseClicked
        try {
            // validacoes
            if (!jTextFieldMainTabNome.getText().isEmpty() && !jFormattedTextPrazo.getText().isEmpty()) {
                Task task = new Task();
                task.setIdProject(project.getId()); // chave estrangeira
                task.setName(jTextFieldMainTabNome.getText());
                task.setDescription(jTextAreaMainTabDescricao.getText());
                task.setNotes(jTextAreaNotas.getText());
                //task.setCompleted(false);

                // Passando um tipo 'Date' | Convertendo de String para DATE
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = null;

                deadline = dateFormat.parse(jFormattedTextPrazo.getText());
                task.setDeadline(deadline);

                // salvando tudo no BD
                controller.save(task);
                JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso | TELA DE CADASTRO TASK");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Tarefa não salva, faltaram campos a serem preenchidos");            
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO ao salvar TAREFA | TELA DE CADASTRO TAREFA" + ex.getMessage());
        }
    }//GEN-LAST:event_jLabelToolBarIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextPrazo;
    private javax.swing.JLabel jLabelMainTabDescricao;
    private javax.swing.JLabel jLabelMainTabNome;
    private javax.swing.JLabel jLabelMainTabNotas;
    private javax.swing.JLabel jLabelMainTabPrazo;
    private javax.swing.JLabel jLabelToolBarIcon;
    private javax.swing.JLabel jLabelToolBarTask;
    private javax.swing.JPanel jPanelMainTab;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneMainTabDescricao;
    private javax.swing.JTextArea jTextAreaMainTabDescricao;
    private javax.swing.JTextArea jTextAreaNotas;
    private javax.swing.JTextField jTextFieldMainTabNome;
    // End of variables declaration//GEN-END:variables

    
    // relacionado ao 'setting' da chave estrangeira
    public void setProject(Project project) {
        this.project = project;
    } 
    
}
